workflows:
  react-native-android:
    name: React Native Android
    environment:
      android_signing:
        - keystore_reference
    scripts:
        - name: Install npm dependencies
          script: | 
            npm install
        - name: Set Android SDK location
          script: | 
            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
        - name: Build Android release
          script: | 
            cd android
            ./gradlew assembleRelease
    artifacts:
            - android/app/build/outputs/**/*.apk
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
        app_id: 1:590334822955:android:e9d3317d1179e9938df86e
        artifact_type: 'apk' 