workflows:
  react-native-android:
    name: React Native Android
    instance_type: mac_mini_m1
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    environment:
      android_signing:
        - keystore_reference
      groups:
        - firebase_credentials
    triggering:
      events:
        - pull_request
      branch_patterns: 
        - pattern: main
      cancel_previous_builds: true
    scripts:
        - name: Install npm dependencies
          script: | 
            npm install
        - name: Set Android SDK location
          script: | 
            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
        - name: Build Android release
          script: | 
            UPDATED_BUILD_NUMBER=$BUILD_NUMBER
            cd android
            ./gradlew assembleRelease \
              -PversionCode=$UPDATED_BUILD_NUMBER \
              -PversionName=3.0.$UPDATED_BUILD_NUMBER
    artifacts:
            - android/app/build/outputs/**/*.apk
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: 1:639844564436:android:f7f704ac32a44b6cc62a41
          artifact_type: 'apk' 
          groups:
            - users